#!/bin/sh

#
# Nagios plugin -- Zookeeper cluster mode
#
# Nagios exit codes: 0=OK, 1=Warning, 2=Critical, 3=Unknown
#

PATH=/usr/local/bin:/usr/bin:/bin
set -e

host=$1
port=$2

[ -z $host ] && echo 'UNKNOWN' && exit 3
[ -z $port ] && echo 'UNKNOWN' && exit 3

echo 'srvr' | nc -N $host $port 2>/dev/null | \
    awk 'BEGIN { state=0 }
         {
             if ($1=="Mode:") {
                 mode=$2
                 if (mode != "follower" && mode != "leader") {
                     state=1
                 }
             }
         }
         END {
             if (NR==0) {
                 print "UNKNOWN no data"; exit (3)
             }
             if (state==1) {
                 print "WARNING", mode; exit (1)
             } else {
                 print "OK", mode; exit (0)
             }
         }'
