#!/bin/sh

#
# Nagios plugin -- check temperature via SNMP
#
# Nagios exit codes: 0=OK, 1=Warning, 2=Critical, 3=Unknown
#

PATH=/usr/local/bin:/usr/bin:/bin
set -e

host=$1
warning=$2
critical=$3

[ -z $host ] && echo UNKNOWN && exit 3
[ -z $warning ] && echo UNKNOWN && exit 3
[ -z $critical ] && echo UNKNOWN && exit 3
[ $warning -gt $critical ] && echo UNKNOWN && exit 3

snmpwalk -c public -v 2c $host 1.3.6.1.4.1.2636.3.1.13.1.7.7 2>/dev/null | \
    awk -vw=$warning -vc=$critical \
        'BEGIN {max=0} {t=$4*1}
         { if (t>=w) { wstate=1 }}
         { if (t>=c) { cstate=1 }}
         { if (t>max) { max=t }}
         END {
             if (NR==0) {
                 print "UNKNOWN no data"; exit (2)
             }
             if (cstate==1) {
                 print "CRITICAL "t" degrees Celsius"; exit (2)
             }
             if (wstate==1) {
                 print "WARNING "t" degrees Celsius"; exit (1)
             } else {
                 print "OK "t" degrees Celsius"; exit (0)
             }
         }'
