#!/bin/sh

#
# Nagios plugin -- check uptime of cluster nodes
#
# Unexpected restarts might go unnoticed because of cluster node redundancy.
#
# Nagios exit codes: 0=OK, 1=Warning, 2=Critical, 3=Unknown
#
# From SNMP:
#     JnxVirtualChassisMemberEntry ::=
#     SEQUENCE {
#         jnxVirtualChassisMemberId             INTEGER,
#         jnxVirtualChassisMemberSerialnumber   DisplayString,
#         jnxVirtualChassisMemberRole           INTEGER,
#         jnxVirtualChassisMemberMacAddBase     MacAddress,
#         jnxVirtualChassisMemberSWVersion      DisplayString ,
#         jnxVirtualChassisMemberPriority       INTEGER,
#         jnxVirtualChassisMemberUptime         INTEGER
#     }
#
# Usage example:
#    ./check_juniper_uptime <hostname> 600
#
# (Note: Integer uptime value will overflow after 68 years)
#

PATH=/usr/local/bin:/usr/bin:/bin
set -e

host=$1
uptime=$2

[ -z $host  ]  && echo UNKNOWN && exit 3
[ -z $uptime ] && echo UNKNOWN && exit 3

oid=1.3.6.1.4.1.2636.3.40.1.4.1.1.1.7

snmpwalk -c public -v 2c -- $host $oid 2>/dev/null | \
    awk -v uptime=$uptime \
        'BEGIN { wstate=0 }
         { if ($4<uptime) { wstate=1 }}
         message=$4" "message
         END {
             if (NR==0) {
                 print "UNKNOWN no data"; exit (3)
             }
             sub(/ $/, "", message)
             if (wstate==1) {
                 print "WARNING uptime < " uptime " (" message ")"; exit (1)
             } else {
                 print "OK uptime > " uptime " (" message ")"; exit (0)
             }
         }'
