#!/bin/sh

#
# Nagios plugin -- check Routing Engine via SNMP
#
# Nagios exit codes: 0=OK, 1=Warning, 2=Critical, 3=Unknown
#

PATH=/usr/local/bin:/usr/bin:/bin
set -e

host=$1

[ -z $host ] && echo UNKNOWN && exit 3

oid=.1.3.6.1.4.1.2636.3.1.13.1.6.9

snmpwalk -c public -v 2c $host $oid 2>/dev/null | \
    awk 'BEGIN { state=0 }
         { if ($4!=2 && $4!=3 && $4!=5 && $4!=7) { state=1 }
           if ($4==1) { message=message" "NR": unknown," } 
           if ($4==2) { message=message" "NR": running," } 
           if ($4==3) { message=message" "NR": ready to run," } 
           if ($4==4) { message=message" "NR": not ready," } 
           if ($4==5) { message=message" "NR": full speed," } 
           if ($4==6) { message=message" "NR": off," } 
           if ($4==7) { message=message" "NR": standby," } 
         }
         END {
             if (NR==0) {
                 print "UNKNOWN no data"; exit (3)
             }
             sub (/,$/, "", message)
             if (state==1) {
                 print "WARNING"message; exit (1)
             } else {
                 print "OK"message; exit (0)
             }
         }'
