#!/bin/sh

#
# Nagios plugin -- Elasticsearch health
#
# Nagios exit codes: 0=OK, 1=Warning, 2=Critical, 3=Unknown
#

PATH=/usr/local/bin:/usr/bin:/bin
set -e

host=$1
port=9200
number_of_datanodes=$2

[ -z $host ]                && echo 'UNKNOWN' && exit 3
[ -z $number_of_datanodes ] && echo 'UNKNOWN' && exit 3

printf 'GET /_cluster/health HTTP/1.0\n\n' | nc -- $host $port 2>/dev/null | \
    awk -F, -vd=$number_of_datanodes \
        '{ if (NR==5 && /^{"cluster_name":/)
               { split ($2, status, ":")
                 split ($4, nnodes, ":")
                 split ($5, dnodes, ":")
                 if (status[2]=="\"green\"" && dnodes[2]==d)
                     { print "OK " status[2] " with "dnodes[2]" datanodes " \
                         nnodes[2] " nodes"; exit (0) }
                 else
                     { print "WARNING " status[2], dnodes[2] " datanodes " \
                         nnodes[2] " nodes"; exit (1) }
               }
         } END {
             if (NR==0) { print "CRITICAL no response"; exit (2) }
         }'
