#!/bin/sh

#
# Nagios plugin -- Check MySQL source of HAproxy health check,
#                  source is a small daemon, testing MySQL lag, etc.
#
# Nagios exit codes: 0=OK, 1=Warning, 2=Critical, 3=Unknown
#

PATH=/usr/local/bin:/usr/bin:/bin
set -e

host=$1
port=$2

[ -z $host ] && echo 'UNKNOWN' && exit 3
[ -z $port ] && echo 'UNKNOWN' && exit 3

status=0
printf 'GET / HTTP/1.0\n\n' | nc $host $port 2>/dev/null | \
    head -1 | grep '^HTTP/1.1 200 OK' >/dev/null || status=1

case $status in
    0) echo "OK"; exit 0 ;;
    1) printf "WARNING"
       printf 'GET / HTTP/1.0\n\n' | nc $host $port 2>/dev/null | \
           head -1 | sed 's/[^ ]* / /' | grep . || printf '\n'
       exit 1 ;;
esac
