#!/bin/sh

#
# Nagios plugin -- check ZFS zpool health
#
# Nagios exit codes: 0=OK, 1=Warning, 2=Critical, 3=Unknown
#

PATH=/sbin:/usr/bin:/bin
set -eu

warning () {
    echo "WARNING zpool $zpool"
    exit 1
}

zpool list -H -o name 2>/dev/null | \
    while read zpool; do
        zpool list -H -o health $zpool | \
            grep ^ONLINE$ >/dev/null || warning
    done

echo "zpool health OK"
